### ISSUE TITLE
Use sqlite to store unsent results

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/RADAR-AndroidApplication#1]
Avro can also be used to locally store results that are not yet transmitted to Kafka. This will ease the compatibility between the Android application and the backend. See for example

https://avro.apache.org/docs/1.7.7/gettingstartedjava.html#Serializing

then we can write, for example:

```java
DatumWriter<BatteryLevel> batteryDatumWriter = new SpecificDatumWriter<BatteryLevel>(BatteryLevel.class);
DataFileWriter< BatteryLevel > dataFileWriter = new DataFileWriter<User>(batteryDatumWriter);
dataFileWriter.create(batteryLevel1.getSchema(), new File("batteryLevel.avro"));
dataFileWriter.append(batteryLevel1);
restSender.send("batteryLevel", myID, batteryLevel1)
dataFileWriter.append(batteryLevel2);
restSender.send("batteryLevel", myID, batteryLevel2)
dataFileWriter.append(batteryLevel3);
restSender.send("batteryLevel", myID, batteryLevel3)
dataFileWriter.close();
```

We can keep track of the last record that was successfully sent to Kafka. Whenever the Android application or server go offline, the records can be retransmitted whenever they reconnect.

**Comment by fnobilia** [comment]
For this purpose the SQL-lite preinstalled on all Android devices should be better. In this way
- we have only one file (e.g. the db file) instead of one file per sensor
- data inside db can be retrieved with normal SLQ query
- we can still keep track of the last record that was successfully sent
- accessing the SQL-lite db is faster than accessing files
- we do not have to take care of multiple files
- data are more compact (memory usage optimisation)
- SQL-Lite natively support multithreading 

https://developer.android.com/training/basics/data-storage/databases.html

**Comment by blootsvoets** [comment]
Ok that sounds better. Let's use sqlite. I'm changing the issue title.

**Comment by blootsvoets** [comment]
Done in sqlStore, I'll make a pull request
