### ISSUE TITLE
Turning the location on upon start up

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-AndroidApplication#22]
Empatica SDK needs to access the location data. Without the location on the SDK does not extract any data from the device.

Granting permission does not entail turning the location on. Upon start-up the app must force the location sensor to be on.

**Comment by blootsvoets** [comment]
You're right the app should make it very clear it cannot collect data without the location permissions.

The Empatica API doesn't use location, but using Bluetooth LE requires location permissions.

**Comment by MaximMoinat** [comment]
We cannot replicate this on the RPi. We await the arrival of the UDOO, before we fix it and/or build in a warning.

For now, I am leaving these references here:
- http://stackoverflow.com/questions/33251373/turn-on-location-services-without-navigating-to-settings-page 
- http://www.android-examples.com/enable-disable-gps-location-service-programmatically-android/

**Comment by fnobilia** [comment]
The sample Empatica app works without turning the location service on. Its [manifest](https://github.com/empatica/empalink-sample-project-android/blob/master/app/src/main/AndroidManifest.xml) does not contain any permissions at all.

**Comment by fnobilia** [comment]
We should take into account that enabling the location service may introduce an ethic problem.

**Comment by blootsvoets** [comment]
The relevant section of the documentation states:

> On all versions of Android, your app needs to declare both the normal and the dangerous permissions it needs in its app manifest, as described in Declaring Permissions. However, the effect of that declaration is different depending on the system version and your app's target SDK level:
> 
> - If the device is running Android 5.1 or lower, or your app's target SDK is 22 or lower: If you list a dangerous permission in your manifest, the user has to grant the permission when they install the app; if they do not grant the permission, the system does not install the app at all.
> - If the device is running Android 6.0 or higher, and your app's target SDK is 23 or higher: The app has to list the permissions in the manifest, and it must request each dangerous permission it needs while the app is running. The user can grant or deny each permission, and the app can continue to run with limited capabilities even if the user denies a permission request.

The target SDK of the Empatica sample app is 22. That means that its code does NOT need to request location permissions, for Bluetooth or anything else. Our target SDK is 24, so since we use Bluetooth, we need to request for these permissions while the app is running.

For the specific link between location and bluetooth in android, see the [Android bug report](https://code.google.com/p/android/issues/detail?id=189090&q=ble%20android%206.0&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars). Their motivation is that since any bluetooth device might itself track its location, and the current device may derive its location from nearby bluetooth devices, any bluetooth LE interaction from Android 6 onwards will need location permissions.

From an ethics point of view, we only send the Bluetooth source ID that we already know the patient has, but we don't couple that to the patient data. We do not collect location data, since we do not store information about devices that were not coupled to the user.

The main activity will check whether location services are enabled.

**Comment by blootsvoets** [comment]
The issues is fixed in 40e9d3f. In this workaround, we revert the target Android API to 22 (Android 5.1). This means fewer recent Android features, but also a less stringent settings management. At any time that we want to increase the API level, we should build some additional on-boarding dialogs to enable location services for Bluetooth.
